name = "bitswap"

[builders]

[builders."docker:go"]
enabled                = true
build_base_image       = "golang:1.17-buster"
enable_go_build_cache  = false # Prevent any eventual bug with version changes
go_proxy_mode          = "direct"

[runners]
  "local:docker" = { enabled = true }
  "cluster:k8s" = { enabled = true }

[global.build_config]
  enable_go_build_cache = false

[[testcases]]
  name = "speed-test"
  instances = { min = 2, max = 100, default = 2 }

  [testcases.params]
  size = { type = "int", desc = "size of file to transfer, in human-friendly form", default = "1MiB" }
  count = { type = "int", desc = "number of transfers", default = "10" }
