include mk/header.mk

CLEAN += $(d)/gotest.json $(d)/gotest.junit.xml

# looks like: we pass the `cat D/gotest.json` generated by a previous rule to gotestsum for formatting.
$(d)/gotest.junit.xml: test/bin/gotestsum coverage/unit_tests.coverprofile
	gotestsum --no-color --junitfile $@ --raw-command cat $(@D)/gotest.json

include mk/footer.mk
